version: '3.1'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx_image
    container_name: nginx_container
    ports:
      - 80:80

  echo_app1:
    image: weshigbee/nginx-echo
    container_name: echo_container_1
    ports:
      - 5000:8080
    hostname: echo1

  email: # Listens on port 8025 internally and 1025 internally for the email server
    image: mailhog/mailhog
    container_name: mailhog_container
